### ISSUE TITLE
项目启动报错，请大佬指导一下

### ISSUE THREAD

**Issue by wendao365** [songcser/gingo#2]
运行cmd/main.go下的main，报错如下
```go
# github.com/fvbock/endless
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:64:11: undefined: syscall.SIGUSR1
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:65:11: undefined: syscall.SIGUSR2
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:68:11: undefined: syscall.SIGTSTP
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:111:13: undefined: syscall.SIGUSR1
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:112:13: undefined: syscall.SIGUSR2
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:115:13: undefined: syscall.SIGTSTP
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:119:13: undefined: syscall.SIGUSR1
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:120:13: undefined: syscall.SIGUSR2
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:123:13: undefined: syscall.SIGTSTP
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: undefined: syscall.Kill
..\..\pkg\mod\github.com\fvbock\endless@v0.0.0-20170109170031-447134032cb6\endless.go:224:11: too many errors
```

**Comment by wendao365** [comment]
希望能够补充一下项目启动的文档

**Comment by songcser** [comment]
#1

**Comment by CUMTB-wangru** [comment]
大佬，请问报错找不到config/config.yaml，还有数据库启动失败，可以分享一下项目启动教程么？


正在使用gin模式的GIN_MODE环境名称,config的路径为config/config.yaml
panic: Fatal error config file: open config/config.yaml: no such file or directory 

goroutine 1 [running]:
github.com/songcser/gingo/initialize.Viper({0x0, 0x0, 0x14000080f28?})
        /Users/wr/gingo/initialize/viper.go:61 +0x7cc
main.main()
        /Users/wr/gingo/cmd/main.go:36 +0x30
exit status 2

**Comment by songcser** [comment]
使用 go run cmd/main.go 命令执行

**Comment by CUMTB-wangru** [comment]
wr@wrMacBookM2Air gingo % go run cmd/main.go 
configEnv == 
gin.Mode() == debug
正在使用gin模式的GIN_MODE环境名称,config的路径为config/config.yaml
zap初始化成功
root:root1234@tcp(db:3306)/gintest?charset=utf8mb4&parseTime=True&loc=Local

2023/07/19 09:53:20 /Users/wr/gingo/initialize/mysql.go:98
[error] failed to initialize database, got error dial tcp: lookup db: no such host
数据库启动失败...

数据库配置改成了：
mysql:
  path: 'db'
  port: '3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'gingo'
  username: 'root'
  password: 'root1234'
  prefix: "t_" # 全局表前缀，单独定义 TableName 则不生效
  singular: false # 是否开启全局禁用复数，true表示不开启
  engine: "" # 引擎，默认InnoDB
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: false

数据库在本地起了，我仅仅改了config.yaml 的数据库配置
![
<img width="1250" alt="image" src="https://github.com/songcser/gingo/assets/90508348/398f7caa-5775-457c-a42a-ffa0e266c05d">
]
大佬，请教一下这个怎么解决？感谢

**Comment by songcser** [comment]
mysql:
path: 'db'
port: '3306'

mysql配置是path应该是localhost吧，本地连接
